In [1]:
%matplotlib inline

import matplotlib.pyplot as plt
import torch

In [2]:
V = torch.load('issue.mat')

# Cuda

## Float precision

In [3]:
V = V.cuda()
V = V.type(torch.float)
assert torch.equal(V, V.transpose(0, 1))

e, _ = torch.symeig(V, eigenvectors=True)
e, _ = torch.sort(e)
e[:5]

tensor([-164.0271, -137.5216, -122.3605,  -49.1825,  -26.5110],
       device='cuda:0')

## Double precision

In [4]:
V = V.cuda()
V = V.type(torch.float)
V = V.type(torch.double)
assert torch.equal(V, V.transpose(0, 1))

e, _ = torch.symeig(V, eigenvectors=True)
e, _ = torch.sort(e)
e[:5]

tensor([-6.9714e-07,  6.8203e-04,  1.3151e-03,  2.6958e-03,  3.3810e-03],
       device='cuda:0', dtype=torch.float64)

# CPU

# Float precision

In [5]:
V = V.cpu()
V = V.type(torch.float)
assert torch.equal(V, V.transpose(0, 1))

e, _ = torch.symeig(V, eigenvectors=True)
e, _ = torch.sort(e)
e[:5]

tensor([-1.6859e+02, -4.7055e+01, -2.3623e+01, -2.0070e+01,  4.9508e-05])

# Double precision

In [6]:
V = V.cuda()
V = V.type(torch.float)
V = V.type(torch.double)
assert torch.equal(V, V.transpose(0, 1))

e, _ = torch.symeig(V, eigenvectors=True)
e, _ = torch.sort(e)
e[:5]

tensor([-6.9714e-07,  6.8203e-04,  1.3151e-03,  2.6958e-03,  3.3810e-03],
       device='cuda:0', dtype=torch.float64)